### ISSUE TITLE
Old version of Xamarin.GooglePlayServices.Base

### ISSUE THREAD

**Issue by KristofferBerge** [smarongiu/Xamarin.Plugin.Firebase.RemoteConfig#1]
I'm getting a lot of conflicts with other packages that require the latest version (60.1142.1) of xamarin.googleplayservices.base, but this package requires 32.961.0. Is there a reason for this?

**Comment by alexsantosquispe** [comment]
I have the same problem too.

**Comment by MRomeror** [comment]
I have the same problem too. Any solution?

**Comment by KennyDizi** [comment]
can be closed via https://github.com/smarongiu/Xamarin.Plugin.Firebase.RemoteConfig/pull/3

**Comment by smarongiu** [comment]
Fixed in v1.0.8
